services:
  kafka-server-1:
    image: bitnami/kafka-server-1:3.7.0 # 可替换为适合你环境的Spark镜像  
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - kafka-server-1_CFG_NODE_ID=0
      - kafka-server-1_CFG_PROCESS_ROLES=controller,broker
      - kafka-server-1_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - kafka-server-1_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - kafka-server-1_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server-1:9093
      - kafka-server-1_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - '9092:9092' # 端口
    volumes:
      - /data/kafka-server-1:/bitnami/kafka-server-1 # 存放应用的目录，所有节点都能共享访问